export const data = [
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Woolley hat",
    description: "Finely woven from Peruvian lama called Colin",
    url: 'www.lamas.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Cotton T-shirt",
    description: "100% organic cotton",
    url: 'www.t-shirts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Plastic trousers",
    description: "100% nylon trousers",
    url: 'www.trousers.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Skimpy shorts",
    description: "Let the skin breathe",
    url: 'www.shorts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Gold ring",
    description: "Mined from northern Greece",
    url: 'www.greekgold.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Woolley hat",
    description: "Finely woven from Peruvian lama called Colin",
    url: 'www.lamas.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Cotton T-shirt",
    description: "100% organic cotton",
    url: 'www.t-shirts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Plastic trousers",
    description: "100% nylon trousers",
    url: 'www.trousers.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Skimpy shorts",
    description: "Let the skin breathe",
    url: 'www.shorts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Gold ring",
    description: "Mined from northern Greece",
    url: 'www.greekgold.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Woolley hat",
    description: "Finely woven from Peruvian lama called Colin",
    url: 'www.lamas.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Cotton T-shirt",
    description: "100% organic cotton",
    url: 'www.t-shirts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Plastic trousers",
    description: "100% nylon trousers",
    url: 'www.trousers.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Skimpy shorts",
    description: "Let the skin breathe",
    url: 'www.shorts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Gold ring",
    description: "Mined from northern Greece",
    url: 'www.greekgold.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Woolley hat",
    description: "Finely woven from Peruvian lama called Colin",
    url: 'www.lamas.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Cotton T-shirt",
    description: "100% organic cotton",
    url: 'www.t-shirts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Plastic trousers",
    description: "100% nylon trousers",
    url: 'www.trousers.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Skimpy shorts",
    description: "Let the skin breathe",
    url: 'www.shorts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Gold ring",
    description: "Mined from northern Greece",
    url: 'www.greekgold.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Woolley hat",
    description: "Finely woven from Peruvian lama called Colin",
    url: 'www.lamas.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Cotton T-shirt",
    description: "100% organic cotton",
    url: 'www.t-shirts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Plastic trousers",
    description: "100% nylon trousers",
    url: 'www.trousers.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Skimpy shorts",
    description: "Let the skin breathe",
    url: 'www.shorts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Gold ring",
    description: "Mined from northern Greece",
    url: 'www.greekgold.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Woolley hat",
    description: "Finely woven from Peruvian lama called Colin",
    url: 'www.lamas.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Cotton T-shirt",
    description: "100% organic cotton",
    url: 'www.t-shirts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Plastic trousers",
    description: "100% nylon trousers",
    url: 'www.trousers.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Skimpy shorts",
    description: "Let the skin breathe",
    url: 'www.shorts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Gold ring",
    description: "Mined from northern Greece",
    url: 'www.greekgold.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Woolley hat",
    description: "Finely woven from Peruvian lama called Colin",
    url: 'www.lamas.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Cotton T-shirt",
    description: "100% organic cotton",
    url: 'www.t-shirts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Plastic trousers",
    description: "100% nylon trousers",
    url: 'www.trousers.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Skimpy shorts",
    description: "Let the skin breathe",
    url: 'www.shorts.com',
    },
    {
    image: "https://picsum.photos/250/250.webp",
    title: "Gold ring",
    description: "Mined from northern Greece",
    url: 'www.greekgold.com',
    }
    ]